### ISSUE TITLE
Complete redesign of tessel.io

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#102]
## What are we doing?

Re-implementation of the tessel.io website both to have both simpler, more maintainable code, and to better highlight the current state/goals of the project.
## Primary goals
- [ ] Clarify what the Tessel project is (not a business). Homepage primary objective should still show what Tessel is, but call to action should orient around getting involved with the project. (https://github.com/tessel/tessel.io/issues/6)
- [ ] Current node.js implementation is overcomplicated, consider moving to a static (or otherwise simpler) implementation
### Secondary goals
- [ ] Fast page loading
- [ ] Better handling of modules, particularly permalinks for ordering per https://github.com/tessel/tessel.io/issues/70
- [ ] Highlight J5IK per https://github.com/tessel/tessel.io/issues/90
- [ ] Roll the [hardware-modules](https://github.com/tessel/hardware-modules) repo into this repo (not useful for it to exist separately)
- [ ] Show the project is not just for hardware people, it's for everyone to get involved in (including designers, web devs who don't have specific interest in microcontrollers, etc.)
- [ ] Reconsider the "Trusted By" section
- [ ] Would be great to be able to have links to educational material (ie Sparkfun's endeavors)
### Implementation details
- [ ] What architecture should we use to emphasize simplicity?
- [ ] How do we create great support for redirects? (some JSON thing?)
## How to get involved

We would really like help from designers, copy editors, and people who are good with usability.
1. Get an account on [Tessel Slack](https://tessel-slack.herokuapp.com/) and join the #website-wg channel
2. Message the channel with a brief message about why you're joining the Learning WG and what you're interested in working on
3. Work away! Message in any relevant Slack channel if you'd like help or direction.
4. Attend the regular Website WG meeting (to be scheduled) to see what others are working on, be part of the community, get help, and share your own progress
## Other

_Using https://github.com/hoodiehq/hood.ie/issues/312 as an example of a great issue defining redesign of this type._

_Some related issues which this redesign should include: https://github.com/tessel/tessel.io/issues/6 <s>https://github.com/tessel/tessel.io/issues/15</s> https://github.com/tessel/tessel.io/issues/70 https://github.com/tessel/tessel.io/issues/90_
### How to join the Slack channel

In the Slack webapp or desktop client, click the word "CHANNELS".
![screen shot 2016-09-07 at 12 28 29 pm](https://cloud.githubusercontent.com/assets/454690/18321406/d9b5b4c2-74fb-11e6-91f4-c39bd1a82346.png)

Search for "website" and the #website-wg channel should pop up. Click to join.
![screen shot 2016-09-07 at 1 04 21 pm](https://cloud.githubusercontent.com/assets/454690/18321426/ee378042-74fb-11e6-9f80-4f0c46463a16.png)

_cc @HipsterBrown @reconbot_

**Comment by rwaldron** [comment]
Some kind of "updates" or "releases" or "latest commits" page?

**Comment by Frijol** [comment]
Re: improving visibility of contributor pathway https://github.com/tessel/tessel.io/issues/112

**Comment by reshusinghhh** [comment]
Hi,I am not able to join Tessle slack channel.It directs to unauthorized issues.

**Comment by Akshitaag** [comment]
Hii , I along with my teammate @rahmeen14 would love to work on redesigning the tessel website as a part of RGSoC 2018.

**Comment by Rahmeen14** [comment]
Hi! Yes, we would love to contribute to the website to make it better. Both of us have been working together for over 7 months now and have built several projects in node. We can assure you of our sincere participation during the SoC

**Comment by sreshu** [comment]
Hi! Me and team partner @miniamisha would love to contribute in designing the website. Already versed with JS,HTML,CSS,MySQL and my team-mate has good experience with hands on python integration with hardware too. We are applying to solve tessel issues for application of RGSoC'18.
